---
  unix_groups:
      tsm:
        name: tsm
        gid: 7000
        state: present
      patrol:
        name: patrol
        gid: 8000
        state: present
  unix_users:
      tsm:
        name: tsm
        uid: 7000
        group: tsm
        password: $6$Fq97C86U$hNSqkGA5mTletZxXBKZTWY80opjmTJG34RiYRheJX6Stt6DDUbLeZYDjyrPOyYlD3tkBDxHJPGmvRTbP9Y9uA0
        comment: "Ususario Backup TSM"
        state: present
      patrol:
        name: patrol
        uid: 8000
        group: patrol
        password: $6$k0758wk9$6nttjE8xxWwDpb6MSWsBVy3dTQ0lkH6RK1T8tsAfbdsn3EY0ii7TTABKVMsKMaAzs36ruVPcOtZv0jmGKg3g60
        comment: "Ususario Monitorizacion Patrol"
        state: present
